name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Build with dotnet
      run: dotnet build --configuration Release ./src/Chromely.sln
    - name: Test with dotnet
      run: dotnet test --configuration Release ./src/Chromely.sln
      
